name: Run Psalm
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none # disable xdebug, pcov
          extensions: curl, date, json, redis, sqlite3, sockets

      - run: composer require --dev vimeo/psalm 4.4.1
        name: Install Psalm

      - run: vendor/bin/psalm --output-format=github --config=.github/workflows/psalm.xml
        name: Run Psalm
